### PR TITLE
Spaces to tabs

### PR DESCRIPTION
**Pull request by BadWolf42**

### CODE REVIEW

**Comment by Domochip** [comment]
Arg, You converted templates.
But templates generated by endusers and provided through community are space indented.
PHP json_encode doesn't offer option to tab indent :-(

**Comment by BadWolf42** [comment]
> Arg, You converted templates.

My converting spree...
Do you want me to revert them ?

**Comment by Domochip** [comment]
Yes, to keep stuff homogeneus and don't add overhead to make space to tab for each new integrated template.
thx 👍

**Comment by Domochip** [comment]
thank you :-)

**Pull request merged**
