### PR TITLE
Fix config leaking on save

### PR DESCRIPTION
**Pull request by BadWolf42**
Fix config leaking on save from Broker tab to Equipment tab (and vice-versa):

Config data from Broker:
image
Should not be present in an Equipment:
image

Fix "Check certificate information": condition was impossible as `_preSaveInformations` was unset

### CODE REVIEW

**Comment by Domochip** [comment]
mm, isn't it a javascript defect?

**Comment by Domochip** [comment]
I've made this cleaning on client side with javascript before eqLogic config is sent to PHP : 91460877c3a02a1c622e76c97633c62a499e0708
Could you tell me more about your last point : Fix "Check certificate information": condition was impossible as _preSaveInformations was unset

**Comment by BadWolf42** [comment]
Regarding the `"Check certificate information": condition was impossible as _preSaveInformations was unset` fix,

On that line: https://github.com/Domochip/jMQTT/blob/91460877c3a02a1c622e76c97633c62a499e0708/core/class/jMQTT.class.php#L495

`$this->_preSaveInformations` is not yet set and so condition is always evaluated as true
That's why I put `$this->_preSaveInformations` construction before this test in this PR.

This flaw/behavior seems to have been introduced in commit https://github.com/Domochip/jMQTT/commit/e6d54ab23a7febdbee77f803094bd6131b25112d

Should I open a new PR for that?

**Comment by Domochip** [comment]
Yes, I think new PR would be better. thx

**Comment by BadWolf42** [comment]
We can now close this issue

**Pull request closed without merging**
