### PR TITLE
Visual modifications

### PR DESCRIPTION
**Pull request by Flobul**
- Rounded advanced configuration button on broker page :
Capture d’écran 2021-05-06 à 10 46 52

- Remove row margin left and right (delete button was a bit cut off) :
Capture d’écran 2021-05-06 à 10 48 37

- And some icons are not square, so were difformed.

### CODE REVIEW

**Review by Flobul — COMMENTED** [review]
Some icons are not square (307 × 352 px), so were distorted

**Comment by Domochip** [comment]
Hi,
First, Thanks a lot for you PR :-)
There is one thing which is not going in the same way as Jeedom Core : Rounded buttons.
There is no more rounded buttons in Jeedom UI or official plugins.
I agree about others stuff but I think rounded buttons is not a good idea.

What's your mind about that?

**Comment by Flobul** [comment]
Hey.
Sure, rouded buttons are still used and roundedLeft and roudedRight are all over officials plugins.
Option should be checked to see it.


I just pointed out one missed rounded on brockers page, all others are already in place all over jMQTT plugin. ;)

**Comment by Domochip** [comment]
OK, got it.
Thanks a lot!!!

**Pull request merged**
